import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({countryNameList}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {
          countryNameList.map((country) => {
            return (
              <div>
                <h4 style={{display: "inline-block"}}>{country.countryName}</h4>
                <p style={{display: "inline-block"}}>{country.countryNameInKR}</p>
              </div>
            );
          })
        }
      </main>
    </div>
  )
}

export async function getStaticProps(context) {

  //The first two lines of code will allow you to use the JSON file right here!
  let response = await fetch("https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/countries.json"); //fetch("...") fetches the JSON file
  let data = await response.json(); //.json() takes JSON file as an input and produces a JS object

  let countryNameList = [];
  data.forEach((country) => {
    countryNameList.push(
      {
        countryName: country.name,
        countryNameInKR: country.translations.kr,
      }
    )
  });

  return {
    props: {
      countryNameList: countryNameList,
    }
  }
}

/*
https://www.codegrepper.com/code-examples/javascript/async%2Fawait+to+fetch+the+json+data
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON#active_learning_working_through_a_json_example

*/

/*
JSON.parse(data) means turning data from string to Javascript object
JSON.stringify(data) means turning data from Javascript object to string
*/